[package]
edition = "2021"
name = "covid-19"
version = "0.1.0"

[dependencies]
chrono = "0.4"
clickhouse = "0.11"
log = "0.4"
num_cpus = "1.14"
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "1.22", features = ["full"]}
tracing = "0.1"
tracing-subscriber = "0.3"
